CREATE TABLE IF NOT EXISTS PRODUCT(
    PRO_ID TEXT PRIMARY KEY,
    PRO_NAME TEXT,
    PRO_PRICE TEXT,
    PRO_COM TEXT
);

INSERT INTO PRODUCT(PRO_ID, PRO_NAME,PRO_PRICE,PRO_COM)
VALUES
    ("101", "LAPTOP", "3200", "DELL"),
    ("102", "MOBILE", "450", "SAMSUNG"),
    ("103", "TABLET", "250", "APPLE"),
    ("104", "HEADPHONES", "550", "BOSE"),
    ("105", "SMARTWATCH", "5000", "FITBIT"),
    ("106", "CAMERA", "900", "CANON"),
    ("107", "PRINTER", "800", "HP"),
    ("108", "MONITOR", "2600", "LG"),
    ("109", "KEYBOARD", "350", "LOGITECH"),
    ("110", "MOUSE", "250", "RAZER");
SELECT PRO_NAME, PRO_PRICE
     FROM PRODUCT
     WHERE PRO_PRICE =
     (SELECT MIN(PRO_PRICE) FROM PRODUCT);
--SELECT PRO_NAME, PRO_PRICE
    -- FROM PRODUCT
    -- WHERE PRO_PRICE =
    -- (SELECT MAX(PRO_PRICE) FROM PRODUCT);
    SELECT MAX(PRO_PRICE) AS MAXIMUM_PRICE FROM PRODUCT;